### PR TITLE
Update dependency and relax version requirements

### PR DESCRIPTION
**Pull request by bachp**
Update debug to the latest version
Relax the version requirement on bluebird and debug

This helps people using npm dedupe

### CODE REVIEW

**Comment by aheckmann** [comment]
Can you explain how a loose semver helps npm dedupe?

**Comment by bachp** [comment]
If one package requires `~2.2.5` and another is using `~2.2.9` but there is also a `2.2.15` available dedupe could use this to satisfy both dependencies.
This is true if the project doesn't break compatibility for patch releases.

If the upstream project adheres tot he semver conventions and increases the versions accordingly, meaning not breaking changes without a major version increase, one could also use the more relaxed `^` notation. So packages requiring `^2.5.6` and `^2.8.9` could also be satisfied by the same dependency version.

**Comment by aheckmann** [comment]
This is the reason I didn't use loose dependencies. I've been bit by upstream packages not using semver correctly, and even done so by mistake a couple times. I'll probably change this back to using specific versions so I can have confidence in my deployments.



—

**Comment by vkarpov15** [comment]
Aaron makes a fair point, merging this was probably not the right choice. I do like the idea of bumping debug, but pegging exact versions is the right choice, especially for bluebird.

**Comment by bachp** [comment]
I agree it's sometimes a problem. That upstream don't adhere to the semver standard. On the other hand the npm eco system is becoming extremely messy because of this. Needing to have 3 version of the same library in a deployment is not really efficient in my opinion.
But I can understand your standpoint as breaking changes in upstream reflect back to your library.

As for deployments I never had a problem as I usually use [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) to pin down exact versions for my tested setup.
I can only recommend this.

**Comment by vkarpov15** [comment]
Even if upstream follows strict semver, mistakes do happen, especially if you aren't an expert in the upstream dependencies. It's not "efficient" in terms of storage space and `npm install` speed, I agree, but those are secondary priorities to shipping a stable module.

**Pull request merged**
