### PR TITLE
Wrong debug output

### PR DESCRIPTION
**Pull request by izatop**
Wrong debug output (it prints a funtion body). More https://github.com/Automattic/mongoose/issues/3005

### CODE REVIEW

**Comment by vkarpov15** [comment]
This is a non-trivial change, because `collectionName` is supported in node driver 1.x but not in 2.x. Also affects all other functions :) I'd imagine `this._collection.collection.name ? this._collection.collection.name : this._collection.collectionName` would be sufficient to get this to work for both 1.x and 2.x.

**Comment by phsstory** [comment]
The same pattern also exists on lines [1678](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L1678), [1730](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L1730), [1814](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L1814), [1968](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L1968), [2035](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L2035), and [2213](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L2213)

Additionally line [2237](https://github.com/izatop/mquery/blob/f78864fdbbd4e0535db16ff10a0b1d1dae9b91fc/lib/mquery.js#L2237) might need a change.

**Comment by Jeff-Lewis** [comment]
It appears @aheckmann [changed all the debug statements](https://github.com/aheckmann/mquery/commit/2628cc231a21bcbaa3b23042c177c1f60500b57e) from `collection.name` to `collectionName` on March 31st for v 1.5.1. 

It appears that `collectionName` is the correct property to use in node driver v2. [See collection.js line 112.](https://github.com/mongodb/node-mongodb-native/blob/2.0/lib/collection.js#L112)

**Comment by phsstory** [comment]
so relating to the original issue Automattic/mongoose#3005, if `collectionName` is collect, are the mongoose dependencies out of date or is this an issue with mongoose on windows?

**Comment by Jeff-Lewis** [comment]
It could be a Windows issue. I am testing updated versions of node 0.12.4 with mongoose 4.0.3 in Windows 8 and I see hundreds of debug statements on my console as `Mongoose: %s.%s(%s) %s %s %s`

**Comment by phsstory** [comment]
I don't see that structure in my instance. Is your npm/mongoose using the compiled or fallback bson?

node 0.12.0
mongoose: 4.0.3

**Comment by Jeff-Lewis** [comment]
fallback bson

**Comment by phsstory** [comment]
that might be our difference, I have full build chains on my windows so I've got the compiled bson from the default npm install.

**Comment by Jeff-Lewis** [comment]
node 0.12.2 and 0.12.4 with mongoose 4.0.3 produces `Mongoose: %s.%s(%s) %s %s %s`. 

node 0.12.2 and 0.12.4 with mongoose 3.8.25 produces the correct debugging statements.

The odd thing is that sometimes in the beginning of the application life cycle, it produces proper output with 4.0.3. Then it somehow gets messed up and starts just out putting `Mongoose: %s.%s(%s) %s %s %s`

**Comment by phsstory** [comment]
I don't see any of that, so I'm guessing it related to the bson fallback code.

have you tried node-gyp before you install mongoose and see if that removes the statements?
Otherwise, I believe we might have a [new issue](https://github.com/Automattic/mongoose/issues/new) for the mongoose issue tracker.

**Comment by Jeff-Lewis** [comment]
It's not a Windows issue, I get the same `Mongoose: %s.%s(%s) %s %s %s` on ubuntu. It's something with our repo I think. I'll create a new issue if needed.

**Comment by izatop** [comment]
I get this behavior with mongodb native driver on Linux with:
* iojs v2.0.2
* mongoose@4.0.3
* mquery@1.5.1 (debug@0.7.4, bluebird@2.9.9)
* mongodb@2.0.30 (readable-stream@1.0.31, mongodb-core@1.1.26)

Test script to reproduce:
```javascript
var m = require('mongoose');
var foo = m.model("foo", {bar: Number});
foo.find({bar: 1}, function (err, it) {
    console.log(it);
});

```

**Comment by vkarpov15** [comment]
Unfortunately, this is an issue with mongoose, see Automattic/mongoose#3005, rather than with mquery. The issue is that mongoose has its own collection abstraction that could use a bit of work and hasn't really kept in lock-step with the driver's collection abstraction. There will be a fix out when mongoose 4.0.6 is released. The use of `collectionName` here is correct for mongodb driver >= 2.0.

**Pull request closed without merging**
