### PR TITLE
Compatibility issue with monk (or possibly mongodriver 2.x or both)

### PR DESCRIPTION
**Pull request by jhsware**
I used mquery with monk and it complained when performing a query. The returned result was an array and not a cursor, so we can't convert it into an arrray again.

### CODE REVIEW

**Comment by vkarpov15** [comment]
Somewhat janky - you should probably use `Array.isArray()` instead. Also please add a test :)

**Comment by jhsware** [comment]
I'll fix the jankiness :D 

But in order to add the test it would be required to add monk as a devDependency for the test. Is this a good idea?

**Comment by vkarpov15** [comment]
If we want to be able to use mquery with monk we're gonna have to test it, so might as well add the devDependency.

**Comment by jhsware** [comment]
Sounds good. I will look into it! There is also an issue with findOneAndUpdate and monk, but I will look at that too.

**Comment by aheckmann** [comment]
This module provides a "node" collection, not a monk collection. As such, you should instead create your own monk wrapper collection and pass that in instead of hacking changes in here.

**Comment by jhsware** [comment]
I see, I was going down the "it seems to work, just need to iron out some minor issues" route...

**Pull request closed without merging**
